version: '3.8'

services:
  pyb-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P#ssw0rd

    networks:
      - pyb-network
  
  pyb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P#ssw0rd
      ME_CONFIG_MONGODB_URL: mongodb://root:P#ssw0rd@pyb-mongodb:27017/
    
    networks:
      - pyb-network

networks:
  pyb-network:
    name: pyb-network
    external: true
